@startuml uc
skinparam linetype ortho
' scale  2/3
left to right direction
actor "Quản trị viên" as ad

package "Mô Hình UseCase Quản lý thông tin Giảng viên" {
  usecase "Quản lý thông tin Giảng viên" as qlttgv
}

ad --> qlttgv

 note right of qlttgv : Thêm, sửa, xóa
@enduml