@startuml uc
skinparam linetype ortho
' scale  2/3
left to right direction
actor "Người dùng" as us
actor "Quản trị viên" as ad

package "Mô Hình UseCase Quản lí đề cương chi tiết" {
  usecase "Quản lý đề cương chi tiết" as qldcct 

}
us --> qldcct
ad --> qldcct

 note right of qldcct : Thêm, sửa, xóa

@enduml