@startuml uc
skinparam linetype ortho
' scale  2/3
left to right direction
actor "Quản trị viên" as ad

package "Mô Hình UseCase Quản lý chương trình đào tạo" {
  usecase "Quản lý chương trình đào tạo" as qlctdt
  usecase "Khoa" as k
  usecase "Ngành" as nganh
  usecase "Khóa" as khoa
  usecase "Học kỳ" as hk 
  usecase "Bộ môn chung" as bmc 
  usecase "Bộ môn riêng" as bmr
}

ad --> qlctdt
qlctdt <. k : extend
qlctdt <. nganh : extend
qlctdt <. khoa : extend
qlctdt <.. hk : extend
qlctdt <.. bmc : extend
qlctdt <.. bmr : extend

 note right of qlctdt : Thêm, sửa, xóa
@enduml