@startuml uc
'skinparam linetype ortho
'scale  2/3
left to right direction
actor "Quản trị viên" as ad
actor "Người dùng" as us

rectangle "**HỆ THỐNG QUẢN LÝ KHUNG CHƯƠNG TRÌNH ĐÀO TẠO VÀ ĐỀ CƯƠNG CHI TIẾT**" {
  usecase "**1.2. Đăng xuất**" as dx
  usecase "**4.1. Quản lý thông tin Giảng viên**" as qlttgv
  usecase "**1.1. Đăng nhập**" as dn
  usecase "**7.1. Quản lý đề cương chi tiết**" as qldcct
  'usecase "Quản lý chương trình đạo tạo" as qlctdt
  usecase "4.3. Xem thông tin giảng viên" as xttgv
  usecase "4.5. Sửa thông tin giảng viên" as sttgv
  usecase "4.4. Đổi mật khẩu" as dmk
  usecase "7.3. Tải xuống đề cương" as txdc
  usecase "7.2. Xem đề cương" as xdc
  'usecase "Xem chương trình đào tạo" as xctdt
  usecase "**2.1. Quản lý Khoa**" as qlk
  usecase "**3.1. Quản lý Ngành**" as qln
  usecase "**7.1. Quản lý học phần**" as qlhp
  usecase "**5.1. Quản lý học kỳ**" as qlhk
  ' quantrivien
  usecase "4.2. Phân quyền người dùng" as pqnd
  usecase "**6.1. Loại học phần**" as lhp
}

us -- dn
ad - dn
qlttgv <.. xttgv : <<extend>>
qlttgv <... dmk : <<extend>>
qlttgv <. sttgv : <<extend>>
us - xttgv
us -- dmk
us - sttgv
qldcct <. txdc : <<extend>>
qldcct <.. xdc : <<extend>>
qlttgv <.. pqnd : <<extend>>
ad -- qlttgv
ad -- dx
us - dx
'qlctdt <. xctdt : <<extend>>
'us --> xctdt
us - qldcct
ad - qlk
ad - qln
ad - qlhp
ad - qlhk
ad - lhp

@enduml